### PR TITLE
Bug Fix and packaged as a gem

### PR DESCRIPTION
**Pull request by unforced**

### CODE REVIEW

**Comment by chasemgray** [comment]
I see the added docs and the packaging as a gem.

What was the bug fix?

Thanks!

**Comment by unforced** [comment]
I'm not sure if it was a bug or just me doing something dumb but the retrieval of cookie using httparty wasn't working so I switched it to just use net/http.

**Comment by chasemgray** [comment]
k, sounds good.

**Comment by chasemgray** [comment]
I also published the gem on rubygems.

**Pull request merged**
